version: '3'

services:
  python:
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    container_name: emwiki-python-deploy
    volumes:
      - static-volume:/emwiki/staticfiles
      - media-volume:/emwiki/mediafiles
    expose:
      - "8001"
    env_file:
      - ./deploy/.env
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: unless-stopped
    container_name: emwiki-db-deploy
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    expose:
      - "5432"
  nginx:
    image: nginx:latest
    container_name: emwiki-nginx-deploy
    expose:
      - "8000"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - static-volume:/staticfiles
      - media-volume:/mediafiles
    depends_on:
      - python
  https-portal:
    image: steveltn/https-portal:1
    container_name: emwiki-https-portal-deploy
    ports:
      - '80:80'
      - '443:443'
    restart: unless-stopped
    environment: 
      DOMAINS: 'emwiki->http://nginx:8000'
      STAGE: 'local'
      # STAGE: 'production' # Don't use production until staging works
    depends_on: 
      - nginx

volumes:
    postgres-data:
    static-volume:
    media-volume:
    emwiki-contents-volume:
