version: '3'

services:
  db:
    image: postgres:latest
    container_name: emwiki-db-develop
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  adminer:
    image: adminer:latest
    container_name: emwiki-adminer-develop
    restart: unless-stopped
    ports: 
      - 8080:8080
    depends_on: 
      - db
