name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        sudo apt-get -y install libpq-dev cmake build-essential python3-dev gcc
        python -m pip install --upgrade pip
    - name: Install python dependecies
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: install -d # Install all dependencies, including development ones
    - name: Test
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: python manage.py test
    - name: Check
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: python manage.py check
