name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8.5, ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.SUB_MODULE_TOKEN }}
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt install cmake libpq-dev python3-dev libssl-dev libffi-dev
        python -m pip install --upgrade pip
        pip -q install pipenv
    - name: Build emparser
      run: |
        pipenv install
        pipenv run python setup.py build
      working-directory: ./emparser
    - name: Install python dependencies
      run: |
        pipenv sync
    - name: Test
      run: |
        pipenv run python ./emwiki/manage.py test
    - name: Check
      run: |
        pipenv run python ./emwiki/manage.py check
