name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: true
    - name: Create docker image
      run: |
        docker compose up -d
    - name: Check codestyle
      run: |
         docker exec pipenv run flake8
    - name: Test
      run: |
         docker exec --workdir /emwiki/emwiki emwiki-python-develop pipenv run coverage run
         docker exec --workdir /emwiki/emwiki emwiki-python-develop pipenv run coverage report
    - name: Test
      run: |
         docker exec emwiki-python-develop export DEBUG=0
         docker exec --workdir /emwiki/emwiki emwiki-python-develop pipenv run python manage.py check --deploy
   
